,0,1,2,3,4,5,6,7,8,9,...,413,414,415,416,417,418,419,420,421,422
0,"[[0.0011306042884990253, 0.8846153846153847, 0...","[[0.0011306042884990253, 0.8846153846153847, 0...","[[0.0011306042884990253, 0.8846153846153847, 0...","[[0.0011306042884990253, 0.8846153846153847, 0...","[[0.0011306042884990253, 0.8846153846153847, 0...","[[0.0011306042884990253, 0.8846153846153847, 0...","[[0.0011111111111111111, 0.8846153846153847, 0...","[[0.0010916179337231969, 0.8717948717948718, 0...","[[0.0010721247563352826, 0.8717948717948718, 0...","[[0.0011111111111111111, 0.8717948717948718, 0...",...,"[[0.002105263157894737, 0.9230769230769231, 0....","[[0.0020857699805068228, 0.9230769230769231, 0...","[[0.002007797270955166, 0.9102564102564102, 0....","[[0.0019688109161793373, 0.9102564102564102, 0...","[[0.0019883040935672514, 0.9102564102564102, 0...","[[0.002007797270955166, 0.9102564102564102, 0....","[[0.0020467836257309943, 0.9102564102564102, 0...","[[0.0021637426900584797, 0.9102564102564102, 0...","[[0.0021247563352826512, 0.9102564102564102, 0...","[[0.0022222222222222222, 0.9102564102564102, 0..."